#Plot4:
household_power_consumption <- read.table("./household_power_consumption.txt",header=TRUE, colClasses=(c("character","character",rep("numeric",7))), sep=";",na.strings = "?")
feb_data4<-subset(household_power_consumption,Date=='1/2/2007' | Date=='2/2/2007',select = c(Date:Sub_metering_3))
Sys.setlocale("LC_TIME", "en_GB.UTF-8")
feb_data4$DateTime<-as.POSIXct(paste(feb_data4$Date,feb_data4$Time),format="%d/%m/%Y %H:%M:%S")
png(filename="plot4.png",width=480,height=480,units="px")
par(mfcol=c(2,2))
plot(x=feb_data4$DateTime, y=feb_data4$Global_active_power,xlab="",ylab="Global Active Power",type="l")
plot(x=feb_data4$DateTime, y=feb_data4$Sub_metering_1,xlab="",ylab="Energy sub metering",type="n")
lines(x=feb_data4$DateTime,y=feb_data4$Sub_metering_1)
lines(x=feb_data4$DateTime,y=feb_data4$Sub_metering_2, col="red")
lines(x=feb_data4$DateTime,y=feb_data4$Sub_metering_3, col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),bty="n",lty=1,col=c("black","red","blue"))
plot(x=feb_data4$DateTime, y=feb_data4$Voltage,xlab="datetime",ylab="Voltage",type="l")
plot(x=feb_data4$DateTime, y=feb_data4$Global_reactive_power,xlab="datetime",ylab="Global_reactive_power",type="l")
dev.off()